/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ApiRouteImport } from './routes/api'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PerfilIndexRouteImport } from './routes/perfil/index'
import { Route as EditarPerfilIndexRouteImport } from './routes/editar-perfil/index'
import { Route as PerfilUserIdIndexRouteImport } from './routes/perfil/$userId/index'
import { Route as guiasGuiasIndexRouteImport } from './routes/(guias)/guias/index'
import { Route as guiasCrearGuiaIndexRouteImport } from './routes/(guias)/crear-guia/index'
import { Route as guiasGuiasGuideIdIndexRouteImport } from './routes/(guias)/guias/$guideId/index'
import { Route as guiasEditarGuiaGuideIdIndexRouteImport } from './routes/(guias)/editar-guia/$guideId/index'

const ApiRoute = ApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilIndexRoute = PerfilIndexRouteImport.update({
  id: '/perfil/',
  path: '/perfil/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditarPerfilIndexRoute = EditarPerfilIndexRouteImport.update({
  id: '/editar-perfil/',
  path: '/editar-perfil/',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilUserIdIndexRoute = PerfilUserIdIndexRouteImport.update({
  id: '/perfil/$userId/',
  path: '/perfil/$userId/',
  getParentRoute: () => rootRouteImport,
} as any)
const guiasGuiasIndexRoute = guiasGuiasIndexRouteImport.update({
  id: '/(guias)/guias/',
  path: '/guias/',
  getParentRoute: () => rootRouteImport,
} as any)
const guiasCrearGuiaIndexRoute = guiasCrearGuiaIndexRouteImport.update({
  id: '/(guias)/crear-guia/',
  path: '/crear-guia/',
  getParentRoute: () => rootRouteImport,
} as any)
const guiasGuiasGuideIdIndexRoute = guiasGuiasGuideIdIndexRouteImport.update({
  id: '/(guias)/guias/$guideId/',
  path: '/guias/$guideId/',
  getParentRoute: () => rootRouteImport,
} as any)
const guiasEditarGuiaGuideIdIndexRoute =
  guiasEditarGuiaGuideIdIndexRouteImport.update({
    id: '/(guias)/editar-guia/$guideId/',
    path: '/editar-guia/$guideId/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api': typeof ApiRoute
  '/editar-perfil': typeof EditarPerfilIndexRoute
  '/perfil': typeof PerfilIndexRoute
  '/crear-guia': typeof guiasCrearGuiaIndexRoute
  '/guias': typeof guiasGuiasIndexRoute
  '/perfil/$userId': typeof PerfilUserIdIndexRoute
  '/editar-guia/$guideId': typeof guiasEditarGuiaGuideIdIndexRoute
  '/guias/$guideId': typeof guiasGuiasGuideIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api': typeof ApiRoute
  '/editar-perfil': typeof EditarPerfilIndexRoute
  '/perfil': typeof PerfilIndexRoute
  '/crear-guia': typeof guiasCrearGuiaIndexRoute
  '/guias': typeof guiasGuiasIndexRoute
  '/perfil/$userId': typeof PerfilUserIdIndexRoute
  '/editar-guia/$guideId': typeof guiasEditarGuiaGuideIdIndexRoute
  '/guias/$guideId': typeof guiasGuiasGuideIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api': typeof ApiRoute
  '/editar-perfil/': typeof EditarPerfilIndexRoute
  '/perfil/': typeof PerfilIndexRoute
  '/(guias)/crear-guia/': typeof guiasCrearGuiaIndexRoute
  '/(guias)/guias/': typeof guiasGuiasIndexRoute
  '/perfil/$userId/': typeof PerfilUserIdIndexRoute
  '/(guias)/editar-guia/$guideId/': typeof guiasEditarGuiaGuideIdIndexRoute
  '/(guias)/guias/$guideId/': typeof guiasGuiasGuideIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api'
    | '/editar-perfil'
    | '/perfil'
    | '/crear-guia'
    | '/guias'
    | '/perfil/$userId'
    | '/editar-guia/$guideId'
    | '/guias/$guideId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api'
    | '/editar-perfil'
    | '/perfil'
    | '/crear-guia'
    | '/guias'
    | '/perfil/$userId'
    | '/editar-guia/$guideId'
    | '/guias/$guideId'
  id:
    | '__root__'
    | '/'
    | '/api'
    | '/editar-perfil/'
    | '/perfil/'
    | '/(guias)/crear-guia/'
    | '/(guias)/guias/'
    | '/perfil/$userId/'
    | '/(guias)/editar-guia/$guideId/'
    | '/(guias)/guias/$guideId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiRoute: typeof ApiRoute
  EditarPerfilIndexRoute: typeof EditarPerfilIndexRoute
  PerfilIndexRoute: typeof PerfilIndexRoute
  guiasCrearGuiaIndexRoute: typeof guiasCrearGuiaIndexRoute
  guiasGuiasIndexRoute: typeof guiasGuiasIndexRoute
  PerfilUserIdIndexRoute: typeof PerfilUserIdIndexRoute
  guiasEditarGuiaGuideIdIndexRoute: typeof guiasEditarGuiaGuideIdIndexRoute
  guiasGuiasGuideIdIndexRoute: typeof guiasGuiasGuideIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/api': {
      id: '/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/': {
      id: '/perfil/'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editar-perfil/': {
      id: '/editar-perfil/'
      path: '/editar-perfil'
      fullPath: '/editar-perfil'
      preLoaderRoute: typeof EditarPerfilIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/$userId/': {
      id: '/perfil/$userId/'
      path: '/perfil/$userId'
      fullPath: '/perfil/$userId'
      preLoaderRoute: typeof PerfilUserIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(guias)/guias/': {
      id: '/(guias)/guias/'
      path: '/guias'
      fullPath: '/guias'
      preLoaderRoute: typeof guiasGuiasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(guias)/crear-guia/': {
      id: '/(guias)/crear-guia/'
      path: '/crear-guia'
      fullPath: '/crear-guia'
      preLoaderRoute: typeof guiasCrearGuiaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(guias)/guias/$guideId/': {
      id: '/(guias)/guias/$guideId/'
      path: '/guias/$guideId'
      fullPath: '/guias/$guideId'
      preLoaderRoute: typeof guiasGuiasGuideIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(guias)/editar-guia/$guideId/': {
      id: '/(guias)/editar-guia/$guideId/'
      path: '/editar-guia/$guideId'
      fullPath: '/editar-guia/$guideId'
      preLoaderRoute: typeof guiasEditarGuiaGuideIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiRoute: ApiRoute,
  EditarPerfilIndexRoute: EditarPerfilIndexRoute,
  PerfilIndexRoute: PerfilIndexRoute,
  guiasCrearGuiaIndexRoute: guiasCrearGuiaIndexRoute,
  guiasGuiasIndexRoute: guiasGuiasIndexRoute,
  PerfilUserIdIndexRoute: PerfilUserIdIndexRoute,
  guiasEditarGuiaGuideIdIndexRoute: guiasEditarGuiaGuideIdIndexRoute,
  guiasGuiasGuideIdIndexRoute: guiasGuiasGuideIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
