/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ApiRouteImport } from './routes/api'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuiasIndexRouteImport } from './routes/guias/index'
import { Route as CrearGuiaIndexRouteImport } from './routes/crear-guia/index'
import { Route as GuiasGuideIdIndexRouteImport } from './routes/guias/$guideId/index'

const ApiRoute = ApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiasIndexRoute = GuiasIndexRouteImport.update({
  id: '/guias/',
  path: '/guias/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrearGuiaIndexRoute = CrearGuiaIndexRouteImport.update({
  id: '/crear-guia/',
  path: '/crear-guia/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiasGuideIdIndexRoute = GuiasGuideIdIndexRouteImport.update({
  id: '/guias/$guideId/',
  path: '/guias/$guideId/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api': typeof ApiRoute
  '/crear-guia': typeof CrearGuiaIndexRoute
  '/guias': typeof GuiasIndexRoute
  '/guias/$guideId': typeof GuiasGuideIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api': typeof ApiRoute
  '/crear-guia': typeof CrearGuiaIndexRoute
  '/guias': typeof GuiasIndexRoute
  '/guias/$guideId': typeof GuiasGuideIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api': typeof ApiRoute
  '/crear-guia/': typeof CrearGuiaIndexRoute
  '/guias/': typeof GuiasIndexRoute
  '/guias/$guideId/': typeof GuiasGuideIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api' | '/crear-guia' | '/guias' | '/guias/$guideId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api' | '/crear-guia' | '/guias' | '/guias/$guideId'
  id:
    | '__root__'
    | '/'
    | '/api'
    | '/crear-guia/'
    | '/guias/'
    | '/guias/$guideId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiRoute: typeof ApiRoute
  CrearGuiaIndexRoute: typeof CrearGuiaIndexRoute
  GuiasIndexRoute: typeof GuiasIndexRoute
  GuiasGuideIdIndexRoute: typeof GuiasGuideIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/api': {
      id: '/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guias/': {
      id: '/guias/'
      path: '/guias'
      fullPath: '/guias'
      preLoaderRoute: typeof GuiasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crear-guia/': {
      id: '/crear-guia/'
      path: '/crear-guia'
      fullPath: '/crear-guia'
      preLoaderRoute: typeof CrearGuiaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guias/$guideId/': {
      id: '/guias/$guideId/'
      path: '/guias/$guideId'
      fullPath: '/guias/$guideId'
      preLoaderRoute: typeof GuiasGuideIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiRoute: ApiRoute,
  CrearGuiaIndexRoute: CrearGuiaIndexRoute,
  GuiasIndexRoute: GuiasIndexRoute,
  GuiasGuideIdIndexRoute: GuiasGuideIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
